[package]
name = "xvf"
version = "0.1.0"
authors = ["Gabriel de Perthuis <g2p.code@gmail.com>"]
description = "Easy archive extraction"
license = "ISC"
repository = "https://github.com/g2p/xvd"
homepage = "https://github.com/g2p/xvd#readme"

[dependencies]
clap = "2"
scmp = "0.1"
lazy_static = "0.2"
tempdir = "0.3"
libc = "0.2"

